### ISSUE TITLE
newby question

### ISSUE THREAD

**Issue by krulkip** [djacobow/alexa_metar#1]
I am new to the echo so wondering how i can install your alexa skill.
I have succeeded with some basic examples so have aws.
krulkip

**Comment by djacobow** [comment]
Hi, krulkip.

If you just want to run this app, you can just wait a little while. I have submitted to Amazon to be a real Alexa skill. I don't know how long it will take to get out there. When it does, it will be called "airport weather."

If you really want to install it for yourself, you'll need to create an AWS account and follow several steps to get a skill running. I would suggest that you go to https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit and go completely through their Alexa Skills Kit  + Lambda demo from start to finish.

Once you've done that, it will be more obvious to you how to deploy the code in this repo. But basically, the idea is that you will have to put the javascript into a Lambda skill and create a new skill and point it at that lambda function. You will also need to paste the contents of a few other files into the appropriate places in the amazon Alexa dev ui.
