### ISSUE TITLE
Really nice work

### ISSUE THREAD

**Issue by PaulDeignan** [djacobow/alexa_metar#2]
Really nice work.  Have been looking in to doing this for awhile.  The other METAR skills a e not nearly as good.  This does just what I wanted.

Let me know if you any specific contributions.

**Comment by djacobow** [comment]
Thanks! The skill is live on Amazon right now if you want to use it as is.

If you want to work on a local copy of your own, I believe that the Echo
"voice model" info on github is a little out of date. Amazon does not make
it easy to sync that.

I have no immediate plans for updates. I have been thinking of:
1. a general tidying up and/or rewrite refactor
2. adding more cities "by name"
3. memcaching of recent lookups (like < 5 minutes old). Not for performance
   but to reduce potential load on ADDS
4. fix any bugs that come up with the metar translation.

Best,
Dave J

**Comment by PaulDeignan** [comment]
I have a local copy running in development.

I didn't see it as a skill on Amazon.  I have tried the Aviation Weather skill and did not like it because it didn't sound correct.  They didn't format the speech at all.

Sent from my iPhone

On Jun 3, 2016, at 5:18 PM, David Jacobowitz <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks! The skill is live on Amazon right now if you want to use it as is.

If you want to work on a local copy of your own, I believe that the Echo
"voice model" info on github is a little out of date. Amazon does not make
it easy to sync that.

I have no immediate plans for updates. I have been thinking of:
1. a general tidying up and/or rewrite refactor
2. adding more cities "by name"
3. memcaching of recent lookups (like < 5 minutes old). Not for performance
   but to reduce potential load on ADDS
4. fix any bugs that come up with the metar translation.

Best,
Dave J

On Fri, Jun 3, 2016 at 1:56 PM, Paul Deignan <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Really nice work. Have been looking in to doing this for awhile. The other
> METAR skills a e not nearly as good. This does just what I wanted.
> 
> Let me know if you any specific contributions.
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/djacobow/alexa_metar/issues/2, or mute the thread
> https://github.com/notifications/unsubscribe/AHK-LoWmxBCorDsuKwBNW-AszzftDsOgks5qIJTqgaJpZM4It5p4
> .

##

**Comment by djacobow** [comment]
Cool. Well, it is there. I believe it is called "METAR Reader" on Amazon.

I think it's pretty close to the way controllers record ATIS, but if you
find anything that is broken and needs fixing, let me know.

Best,
Dave J

**Comment by PaulDeignan** [comment]
I did find it and installed it from Amazon.  So far, so good.

Again, really nice work.

Sent from my iPad

On Jun 3, 2016, at 10:43 PM, David Jacobowitz <notifications@github.com<mailto:notifications@github.com>> wrote:

Cool. Well, it is there. I believe it is called "METAR Reader" on Amazon.

I think it's pretty close to the way controllers record ATIS, but if you
find anything that is broken and needs fixing, let me know.

Best,
Dave J

On Fri, Jun 3, 2016 at 3:14 PM, Paul Deignan <notifications@github.com<mailto:notifications@github.com>>
wrote:

> I have a local copy running in development.
> 
> I didn't see it as a skill on Amazon. I have tried the Aviation Weather
> skill and did not like it because it didn't sound correct. They didn't
> format the speech at all.
> 
> Sent from my iPhone
> 
> On Jun 3, 2016, at 5:18 PM, David Jacobowitz <notifications@github.com<mailto:notifications@github.com>
> mailto:notifications@github.com> wrote:
> 
> Thanks! The skill is live on Amazon right now if you want to use it as is.
> 
> If you want to work on a local copy of your own, I believe that the Echo
> "voice model" info on github is a little out of date. Amazon does not make
> it easy to sync that.
> 
> I have no immediate plans for updates. I have been thinking of:
> 1. a general tidying up and/or rewrite refactor
> 2. adding more cities "by name"
> 3. memcaching of recent lookups (like < 5 minutes old). Not for performance
>    but to reduce potential load on ADDS
> 4. fix any bugs that come up with the metar translation.
> 
> Best,
> Dave J
> 
> On Fri, Jun 3, 2016 at 1:56 PM, Paul Deignan <notifications@github.com<mailto:notifications@github.com>
> mailto:notifications@github.com>
> wrote:
> 
> > Really nice work. Have been looking in to doing this for awhile. The
> > other
> > METAR skills a e not nearly as good. This does just what I wanted.
> > 
> > Let me know if you any specific contributions.
> > 
> > ## 
> > 
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/djacobow/alexa_metar/issues/2, or mute the thread
> > <
> > https://github.com/notifications/unsubscribe/AHK-LoWmxBCorDsuKwBNW-AszzftDsOgks5qIJTqgaJpZM4It5p4
> > 
> > .
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub<
> https://github.com/djacobow/alexa_metar/issues/2#issuecomment-223697028>,
> or mute the thread<
> https://github.com/notifications/unsubscribe/ABrvqJ_P6nQolrKKK-OkPqae8ShYllDZks5qIJomgaJpZM4It5p4
> 
> > .
> 
> ## 
> 
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/djacobow/alexa_metar/issues/2#issuecomment-223707509,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHK-Lip1cX411dgZ87cjNipdjm5FPFI3ks5qIKdRgaJpZM4It5p4
> .

##
