### ISSUE TITLE
Visibility is reported before winds

### ISSUE THREAD

**Issue by squawkingVFR** [djacobow/alexa_metar#3]
The visibility is reported before the winds when retrieving the METAR. Winds should come before visibility.

**Comment by djacobow** [comment]
You're right. I don't know how I got that reversed. I'll fix it presently.

-- dgj

**Comment by djacobow** [comment]
Fixed in https://github.com/djacobow/alexa_metar/commit/d520ec88ec86bb615bb30cbeb2b7d48bfde1cb72

and live on Amazon now.

**Comment by squawkingVFR** [comment]
That worked! Thanks!
